server:
  port: 8080
predefined-image-types:
  original:
    height: 200
    width: 200
    quality: 50
    scale-type: CROP
    fill-color: #2311d2'
    type: JPG
  thumbnail:
    height: 50
    width: 50
    quality: 50
    scale-type: Skew
    fill-color: '#2311d2'
    type: PNG